# MODEL_BUILDING

In [3]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Activation, Flatten
from tensorflow.keras.layers import Conv2D, MaxPooling2D
import pickle

In [4]:
pickle_in = open("X.pickle","rb")
X = pickle.load(pickle_in)

pickle_in = open("y.pickle","rb")
y = pickle.load(pickle_in)

In [5]:
#normalize
#X = tf.keras.utils.normalize(X, axis=1)
#y = tf.keras.utils.normalize(y, axis=1)
#----------------or -------------------
X = X/255.0
print(X[0])
#plt.imshow(X[0:],cmap='gray')
#plt.show()

[[[0.45882353]
  [0.47058824]
  [0.41568628]
  ...
  [0.53333336]
  [0.5294118 ]
  [0.52156866]]

 [[0.46666667]
  [0.4745098 ]
  [0.42352942]
  ...
  [0.5372549 ]
  [0.5372549 ]
  [0.53333336]]

 [[0.47058824]
  [0.48235294]
  [0.43137255]
  ...
  [0.5529412 ]
  [0.5411765 ]
  [0.5411765 ]]

 ...

 [[0.27450982]
  [0.3137255 ]
  [0.28627452]
  ...
  [0.25490198]
  [0.2901961 ]
  [0.32156864]]

 [[0.29411766]
  [0.3019608 ]
  [0.30588236]
  ...
  [0.30980393]
  [0.34117648]
  [0.30588236]]

 [[0.28235295]
  [0.28235295]
  [0.2784314 ]
  ...
  [0.36078432]
  [0.2901961 ]
  [0.28627452]]]


In [ ]:
model = Sequential()

model.add(Conv2D(256, (3, 3), input_shape=X.shape[1:]))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(256, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Flatten())  # this converts our 3D feature maps to 1D feature vectors

model.add(Dense(64))

model.add(Dense(1))
model.add(Activation('sigmoid'))

model.compile(loss='binary_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

model.fit(X, y, batch_size=32, epochs=3, validation_split=0.3)

Instructions for updating:
Colocations handled automatically by placer.
Train on 140 samples, validate on 60 samples
Instructions for updating:
Use tf.cast instead.
Epoch 1/3


In [ ]:
x_test = X
y_test =y

In [ ]:
val_loss, val_acc = model.evaluate(x_test, y_test)
print(val_loss)
print(val_acc)

In [ ]:
#saveing get mode by using keras like pickel
#save
model.save('cat_dog_model.model')
#get
cat_dog_model = tf.keras.models.load_model('cat_dog_model.model')

In [ ]:
model.summary()

In [ ]:
#predictions
predictions = cat_dog_model.predict(X)
print(predictions)

In [ ]:
import numpy as np
print(np.argmax(predictions[0]))

In [ ]:
#plt.imshow(X[0],cmap='gray')
#plt.show()

In [ ]:
# Viewing model_configuration

model.summary()
model.get_config()
model.layers[0].get_config()
model.layers[0].input_shape
model.layers[0].output_shape
model.layers[0].get_weights()
np.shape(model.layers[0].get_weights()[0])
model.layers[0].trainable